<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWcqkglq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWcqkglq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWcqkglq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWcqkglq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWcqkglq\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wcqkglq',
    'container.build_id' => 'daa7e1bc',
    'container.build_time' => 1518430564,
));
