<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPn56yun\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPn56yun/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPn56yun.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPn56yun\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPn56yun\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pn56yun',
    'container.build_id' => '61e37665',
    'container.build_time' => 1519459299,
));
