<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8nxgnvq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8nxgnvq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8nxgnvq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8nxgnvq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8nxgnvq\appDevDebugProjectContainer(array(
    'container.build_hash' => '8nxgnvq',
    'container.build_id' => '49e9924b',
    'container.build_time' => 1519140106,
));
